# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

  # Position Controllers ---------------------------------------
joint0_position_controller:
  type: effort_controllers/JointPositionController
  joint: joont0
  pid: {p: 2000, i: 100, d: 500}

joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joont1
  pid: {p: 2000, i: 100, d: 500}

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joont2
  pid: {p: 2000, i: 100, d: 500}